### ISSUE TITLE
Issue with a code?

### ISSUE THREAD

**Issue by lkolchin** [iopipe/awslambda-reverse-proxy#3]
Hi,

Seems that there is an error somewhere in this code:

```
'use strict';
const http = require('http')
const url = require('url')

var signRequest = (requestOptions) => { return requestOptions }
if (process.env.AWS_SIGN_REQUESTS) {
  signRequest = require('aws4').sign
}

const httpAgent = http.Agent({
  keepAlive: true,
  keepAliveMsecs: 300000
})

module.exports.handler = (event, context, callback) => {
  console.log('event: ' + JSON.stringify(event));

  var res = http.request(signRequest({
    hostname: process.env.URL,
    method: event.httpMethod,
    headers: event.headers,
    path: event.path,
    agent: httpAgent,
    timeout: 30 /* maximum time for api gateway invoked Lambda */
  }))

  console.log('request: ' + JSON.stringify(res));

  var resBody = ""
  res.on('data', (chunk) => {
    resBody += chunk
  })
  .on('end', () => {
    var response = {
      statusCode: res.statusCode,
      headers: res.headers,
      body: resBody
    }
    console.log(response)
    callback(null, response)
  })
};
```

I'm getting this:
```
2020-08-18T08:58:23.503Z	1b7c12b2-23b1-4e70-bed0-323ae1b2f8f7	ERROR	Uncaught Exception 	
{
    "errorType": "Error",
    "errorMessage": "socket hang up",
    "code": "ECONNRESET",
    "stack": [
        "Error: socket hang up",
        "    at connResetException (internal/errors.js:609:14)",
        "    at Socket.socketOnEnd (_http_client.js:453:23)",
        "    at Socket.emit (events.js:327:22)",
        "    at endReadableNT (_stream_readable.js:1221:12)",
        "    at processTicksAndRejections (internal/process/task_queues.js:84:21)"
    ]
}
```

The func config looks like this:

```
  apiproxyfunction:
    handler: src/handler.handler
    events:
      - http:
          path: /
          method: any
          #integration: lambda
          cors: true
          # private: true
    environment:
      URL: 'pokeapi.co'
```

Can you please have a quick look?
